version: '3.9'
services:
  db:
    image: postgres:16
    container_name: quaint_portal_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: quaint_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
